// app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Geist_Mono, Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";

// 1. SANS: For standard UI and body text
const fontSans = Inter({
	subsets: ["latin"],
	variable: "--font-sans", // Standard Tailwind naming
});

// 2. MONO: For terminal readouts and data strings
const fontMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
	// adjustFontFallback: 'Arial', // Prevents the "Size Jump" if font takes time to load
});
// 3. DISPLAY: For aggressive "BASE 60" headings
const fontDisplay = Space_Grotesk({
	subsets: ["latin"],
	variable: "--font-display",
});

// 1. BASE DOMAIN CONFIGURATION
// Replace with your actual Vercel deployment URL
const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://base-60.vercel.app/";

export const metadata: Metadata = {
	// 1. IDENTITY & TITLE TEMPLATE
	metadataBase: new URL(BASE_URL),
	title: {
		default: "BASE 60 // Global Hardware Foundry",
		template: "%s // BASE 60", // Child pages will show: "Product Name // BASE 60"
	},
	description: "Precision-engineered computer hardware dispatched from Babylon to the world. Configure your legacy in the Crucible 3D Architect.",
	applicationName: "BASE 60",

	// 2. AUTHORSHIP
	authors: [{ name: "BASE 60 Engineering", url: BASE_URL }],
	creator: "BASE 60",
	publisher: "BASE 60 Logistics",

	// 3. SEO KEYWORDS
	keywords: ["PC Builder", "3D Configurator", "RTX 5090", "Gaming PC", "Hardware Foundry", "TechSouq", "Babylon Tech", "Custom Workstation", "High Performance Computing", "PC Components Iraq"],

	// 4. ROBOT INSTRUCTIONS
	robots: {
		index: true,
		follow: true,
		nocache: false,
		googleBot: {
			index: true,
			follow: true,
			noimageindex: false,
			"max-video-preview": -1,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},

	// 5. OPEN GRAPH (Facebook, LinkedIn, Discord)
	openGraph: {
		type: "website",
		locale: "en_US",
		url: BASE_URL,
		title: "BASE 60 // The Hardware Foundry",
		description: "Configure. Analyze. Deploy. The world's first logic-aware 3D PC builder from Babylon.",
		siteName: "BASE 60",
		// Images are auto-generated by app/opengraph-image.tsx
	},

	// 6. TWITTER / X
	twitter: {
		card: "summary_large_image",
		title: "BASE 60 // Global Hardware Foundry",
		description: "Precision hardware from Babylon. Enter the Crucible.",
		creator: "@base60_foundry", // Replace with your actual handle
		// Images are auto-generated by app/twitter-image.tsx
	},

	// 8. CATEGORIZATION
	category: "technology",
	classification: "e-commerce",
	referrer: "origin-when-cross-origin",
};

// 9. VIEWPORT SETTINGS (Separate export in Next.js 14+)
export const viewport: Viewport = {
	themeColor: "#0A0E14", // Matches your Midnight background
	width: "device-width",
	initialScale: 1,
	maximumScale: 1, // Prevents auto-zoom on inputs, critical for mobile forms
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning className="dark">
			<body
				className={`
				${fontSans.variable} 
				${fontMono.variable} 
				${fontDisplay.variable} 
				bg-[#0A0E14] text-[#F5F5F0] antialiased font-sans dark
			`}
			>
				<main>{children}</main>
				<Toaster position="bottom-left" />
				<Analytics />
			</body>
		</html>
	);
}
